// Both of these suggestions from ReSharper should be ignored.  If the properties are private or 'get-only' then they
// can't be De/Serialized properly
// ReSharper disable AutoPropertyCanBeMadeGetOnly.Global
// ReSharper disable MemberCanBePrivate.Global

// This was regarding the GetHashCode function generated by Rider which ReSharper then complained about it
// ReSharper disable NonReadonlyMemberInGetHashCode

namespace ConfigurationTest.Configs;

public class OtherTestConfig : IEquatable<OtherTestConfig>
{
	public object? Anything { get; set; } = "Just something random";
	public long Long { get; set; } = 123456789101112;
	// Things below here are breaking one or more of the implementations
	// public List<string> Text { get; set; } = new() { "Testing", "1, 2, 3" };
	// public char Char { get; set; } = 'a';
	// public Guid Guid { get; set; } = Guid.NewGuid();
	// public DateOnly DateOnly { get; set; } = DateOnly.FromDateTime(DateTime.Now);
	// public DateTime DateTime { get; set; } = DateTime.Now;
	// public TestId Id { get; set; } = TestId.Everything;

	public bool Equals(OtherTestConfig? other)
	{
		if (ReferenceEquals(null, other)) return false;
		if (ReferenceEquals(this, other)) return true;
		return Equals(Anything, other.Anything)
		       && Long == other.Long
		       // && Text.SequenceEqual(other.Text)
		       // && DateOnly == other.DateOnly
		       // && Equals(Id, other.Id)
		       // && Text.SequenceEqual(other.Text)
		       // && Char == other.Char
			;
	}

	public override bool Equals(object? obj)
	{
		if (ReferenceEquals(null, obj)) return false;
		if (ReferenceEquals(this, obj)) return true;
		return obj.GetType() == GetType()
		       && Equals((OtherTestConfig)obj);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(Anything, Long);
	}
}